Create database QLQCafe
GO
USE [QLQCafe]
GO
/****** Object:  Table [dbo].[NhanVien]    Script Date: 12/02/2017 22:27:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhanVien](
	[MaNV] [nchar](5) NOT NULL,
	[TenNV] [nvarchar](30) NULL,
	[GioiTinh] [nchar](5) NULL,
	[NgaySinh] [datetime] NULL,
	[SDT] [nvarchar](11) NULL,
	[DiaChi] [nvarchar](30) NULL,
	[Hinh] [ntext] NULL,
 CONSTRAINT [PK_NhanVien] PRIMARY KEY CLUSTERED 
(
	[MaNV] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

/****** Object:  Table [dbo].[QuyenTruyCap]    Script Date: 12/02/2017 22:28:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QuyenTruyCap](
	[MaTC] [nchar](20) NOT NULL,
	[MaNV] [nchar](5) NOT NULL,
	[MucDoTC] [int] NULL,
	[MatKhau] [nchar](20) NULL,
 CONSTRAINT [PK_QuyenTruyCap_1] PRIMARY KEY CLUSTERED 
(
	[MaTC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[QuyenTruyCap]  WITH CHECK ADD  CONSTRAINT [FK_QuyenTruyCap_NhanVien] FOREIGN KEY([MaNV])
REFERENCES [dbo].[NhanVien] ([MaNV])
GO
ALTER TABLE [dbo].[QuyenTruyCap] CHECK CONSTRAINT [FK_QuyenTruyCap_NhanVien]

/****** Object:  Table [dbo].[LOAIDAU]    Script Date: 12/02/2017 22:28:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAIDAU](
	[MALOAIDAU] [int] IDENTITY(1,1) NOT NULL,
	[TENLOAIDAU] [nvarchar](50) NULL,
	[HIEN] [int] NULL,
 CONSTRAINT [PK__LOAIDAU__4AB81AF0] PRIMARY KEY CLUSTERED 
(
	[MALOAIDAU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[CHITIETDAU]    Script Date: 12/02/2017 22:28:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETDAU](
	[MADAU] [int] IDENTITY(1,1) NOT NULL,
	[TENDAU] [nvarchar](50) NOT NULL,
	[MALOAIDAU] [int] NOT NULL,
	[DONGIA] [float] NOT NULL,
	[SOLUONGTONKHO] [int] NULL,
	[HIEN] [int] NULL,
	[HINH] [ntext] NULL,
 CONSTRAINT [PK__CHITIETDAU__4CA06362] PRIMARY KEY CLUSTERED 
(
	[MADAU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE [dbo].[CHITIETDAU]  WITH CHECK ADD  CONSTRAINT [FK_LOAIDAU_MALOAIDAU] FOREIGN KEY([MALOAIDAU])
REFERENCES [dbo].[LOAIDAU] ([MALOAIDAU])
GO
ALTER TABLE [dbo].[CHITIETDAU] CHECK CONSTRAINT [FK_LOAIDAU_MALOAIDAU]

---- Insert NhanVien -------
Insert into NhanVien values ('001', N'Lai Hùng Phương', N'Nam', GETDATE(), 0975678319, N'Bình Thạnh', NULL)
Insert into NhanVien values ('002', N'Nguyễn Minh Thiện', N'Nam', GETDATE(), 0961538892, N'Sài Gòn', NULL)
Insert into NhanVien values ('003', N'Nguyễn Quỳnh Như', N'Nữ', GETDATE(), 01653874206 , N'Cần Thơ' , NULL)
Insert into NhanVien values ('004', N'Hoàng Quỳnh Như', N'Nữ', GETDATE(), 0974502316, N'Hà Nội', NULL)

--- Insert Table QuyenTruyCap ----
Insert into QuyenTruyCap values('admin', '003', 3, 'root')

-----Insert Table LoaiDAU--------
INSERT INTO LOAIDAU VALUES(N'Cafe', 1)
INSERT INTO LOAIDAU VALUES(N'Nước giải khát', 1)
INSERT INTO LOAIDAU VALUES(N'Đồ ăn', 1)
INSERT INTO LOAIDAU VALUES(N'Khác', 1)
-----End Insert Table LoaiDAU--------


-----Insert Table CHITIETDAU--------
INSERT INTO CHITIETDAU VALUES ( N'Cafe Robusta', 1, 17000, 100, 1, NULL)
INSERT INTO CHITIETDAU VALUES ( N'Cafe Culi', 1, 17000, 120, 1, NULL)
INSERT INTO CHITIETDAU VALUES ( N'Cafe Moka', 1, 30000, 87, 1, NULL)
INSERT INTO CHITIETDAU VALUES ( N'Cafe Ro-Mo', 1, 19000, 48, 1, NULL)
INSERT INTO CHITIETDAU VALUES ( N'Cafe Arabica', 1, 15000, 396, 1, NULL)
INSERT INTO CHITIETDAU VALUES ( N'Coca', 2, 10000, 38, 1, NULL)
INSERT INTO CHITIETDAU VALUES ( N'7Up', 2, 10000, 74, 1, NULL)
INSERT INTO CHITIETDAU VALUES ( N'Sá xị', 2, 11000, 193, 1, NULL)
INSERT INTO CHITIETDAU VALUES ( N'Kem Dâu', 3, 7000, 57, 1, NULL)
INSERT INTO CHITIETDAU VALUES ( N'Kem Cafe', 3, 7000, 63, 1, NULL)
INSERT INTO CHITIETDAU VALUES ( N'Trái cây to', 3, 15000,24, 1, NULL)
INSERT INTO CHITIETDAU VALUES ( N'Khăn ướt', 4, 2000, 432, 1, NULL)